### ISSUE TITLE
Binary distribution

### ISSUE THREAD

**Issue by denisdemais** [kifferltd/open-mika#2]
Hi. Congratulations for your project.

Do you have a binary distribution (release) ? (win32, linux)

If not, how i can build this.

Thanks!

**Comment by kiffer580** [comment]
HI denisdemais,
Sorry I didn't spot your message until now.
Currently there is no binary distribution online; we used to have a public svn server where you could also download a "nightly build", now we have replaced the svn server with github but we are still working on a solution for CI and binary distributions.  In fact it was while working on that that I saw your message!
I can send you a build for linux/x86 if that helps - or for arm, mips etc. but then I need to know about your toolchain etc..

Best regards

Chris Gray

**Comment by denisdemais** [comment]
Hi, Cris.

Do you can build a win32 (32-bit) version?

open-mika have support to network ?

Kind regards,
Thanks!

**Comment by vadosnaprimer** [comment]
Hello. May I have a linux x86 build please? Otherwise, what is the game compatibility compared to existing j2me emulators?
